In [0]:
import numpy as np

In [0]:
#Create one dimensional array
onedarray = np.array([1,2,3,4,5])

In [0]:
onedarray.shape #To check the shape(dimension) of the array

(5,)

In [0]:
onedarray2 = np.array([1,2,3,4,5])

In [0]:
#Arithmetic operations
result = onedarray + onedarray2
result

array([ 2,  4,  6,  8, 10])

In [0]:
#Two dimensional Array
twodexample = np.array([[1,2],[3,4]])
twodexample

array([[1, 2],
       [3, 4]])

In [0]:
twodexample.shape

(2, 2)

In [0]:
result2d = twodexample + twodexample
result2d

array([[2, 4],
       [6, 8]])

In [0]:
#Pandas --- Data Analysis and Manipulation library
#to preserve the structure of the data.
#Import pandas library
import pandas as pd

In [0]:
employee = pd.read_csv("/home/ubuntu/MachineLearning/Day3/employee.csv", header = None, names=['eid','ename','esal'])

In [0]:
employee

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [0]:
employee2 =pd.read_csv('employeeWithHeaders.csv')

In [0]:
employee2

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [0]:
employee[(employee.esal > 3000) & (employee.ename == 'Utkarsha')]

eid     ename  esal  YearlySal
3    4  Utkarsha  9878     118536

In [0]:
#iloc[row range/list,column range/list]
employee.iloc[:,:] #Series

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [0]:
employee.iloc[:,1:3] 

ename  esal
0  Prashant  1000
1      Amar  2000
2    Chitra  2000
3  Utkarsha  9878
4      Ajit  9999

In [0]:
employee.loc[:,['eid','esal']]

eid  esal
0    1  1000
1    2  2000
2    3  2000
3    4  9878
4    5  9999

In [0]:
employee[['eid','ename']]

eid     ename
0    1  Prashant
1    2      Amar
2    3    Chitra
3    4  Utkarsha
4    5      Ajit

In [0]:
employee

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [0]:
yearlySalary = employee.esal * 12
yearlySalary

0     12000
1     24000
2     24000
3    118536
4    119988
Name: esal, dtype: int64

In [0]:
employee['YearlySal'] = yearlySalary
employee

eid     ename  esal  YearlySal
0    1  Prashant  1000      12000
1    2      Amar  2000      24000
2    3    Chitra  2000      24000
3    4  Utkarsha  9878     118536
4    5      Ajit  9999     119988

In [0]:
employee.to_csv('finalDataset.csv' , index= False)

In [0]:
dataframeExample = pd.DataFrame(np.array(range(1,10)).reshape(3,3))

In [0]:
dataframeExample

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9